name: Frends.Edifact.ConvertToJson Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/release.yml@main
    with:
      workdir: Frends.Edifact.ConvertToJson
    secrets:
      build_time_nuget_feed_url: ${{ secrets.PRIVATE_NUGET_FEED_URL }}
      build_time_nuget_feed_api_key: ${{ secrets.PRIVATE_NUGET_FEED_API_KEY }}
      feed_api_key: ${{ secrets.TASKS_FEED_API_KEY }}