name: Frends.Edifact.CreateFromXml Test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Edifact.CreateFromXml/**'
      - 'Frends.Edifact.CreateFromXml.Tests/**'
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@main
    with:
      workdir: Frends.Edifact.CreateFromXml
    secrets:
      build_time_nuget_feed_url: ${{ secrets.PRIVATE_NUGET_FEED_URL }}
      build_time_nuget_feed_api_key: ${{ secrets.PRIVATE_NUGET_FEED_API_KEY }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      
