name: Frends.Edifact.ConvertToJson Test

on:
  push:
    branches-ignore: 
      - main
    paths:
      - 'Frends.Edifact.ConvertToJson/**'
      - 'Frends.Edifact.ConvertToJson.Tests/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_test.yml@custom-feed-feature
    with:
      workdir: Frends.Edifact.ConvertToJson
    secrets:
      custom_nuget_feed_url: ${{ secrets.PRIVATE_NUGET_FEED_URL }}
      custom_nuget_feed_api_key: ${{ secrets.PRIVATE_NUGET_FEED_API_KEY }}
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      